My bash lab 3

diff --git a/bash/bashlab3 b/bash/bashlab3
--- a/bash/bashlab3
+++ b/bash/bashlab3
@@ -1,16 +1,23 @@
 #!/bin/bash
 #My Bash lab 3
 
-echo "Step1. Installing LXD in the VM"
-echo "----------"
-#checking if lxd is installed or not. I had used which lxd command to find this location 
-
-if [ -e "/snap/bin/lxd" ]; then
-    echo "Output = lxd is already installed in the VM"
+#use the which command to see if we have lxd on the system already
+which lxd >/dev/null
+if [ $? -ne 0 ]; then
+	# need to install lxd
+	echo "Installing lxd - you may have to enter your password to install it"
+	sudo snap install lxd
+	if [ $? -ne 0 ]; then
+	#failed to install lxd - exit with an error message and status
+		echo "Failed to install lxd software which is require."
+		exit 1
+	fi
 else
-    "$(sudo snap install lxd)"
-        echo "lxd installed successfully"
+echo "Step1. Installing LXD in the vm"
+echo "---------"
+echo "Output = lxd is already installed in the vm"
 fi
+
 echo "----------"
 echo "----------"
 
@@ -19,4 +26,3 @@ echo "----------"
 #running lxbr0 in the vm using lxd init --auto
 $(lxd init --auto)
 echo "Output = lxbr0 is created"
-
